### PR TITLE
Enhancement: Added trait to class for addHook

### PR DESCRIPTION
**Pull request by ghost**
**This pull request is not ready. This is more for a review of approach**

I implemented a trait and like how its beginning to shape up. I think it might be useful to find a way to include the flash functionality in this trait as well, though I didn't spend too much time on it. Let me know what you think and I can make edits 👍

### CODE REVIEW

**Comment by hahnzilla** [comment]
Cool cool! This is actually super relevant to https://github.com/Moment-Inc/craft-fbpixel/issues/8

**Comment by ghost** [comment]
Yeah, I can keep working on this if you'd like 👍 I don't know if you have a PR for this coming up?

**Comment by hahnzilla** [comment]
I haven't started on it. Have at it!

**Comment by ghost** [comment]
Happy where this is going, need better naming, but aside from that most of what I have to do is cleanup. One open item is how to refactor `$this->variantIds = craft()->userSession->getFlash(self::FLASH_NAME, null, true);` within the checkFlash method.

**Pull request closed without merging**
